public with sharing class LeadManager {
    
    /**
     * createNewLead  A webservice method to create a lead record with the lease information. 
     *  
     * @param  lastName    lastName of lead
     * @param  firstName   firstName lead
     * @param  companyName companyName lead
     * @param  email       email lead
     * @param  phone       phone lead
     * @return             return description
     */ 
    webservice static String createNewLead(String lastName, String firstName, String companyName, String email, String phone){

    }
}
