public with sharing class IntegrationConstants {
    public static final String ENDPOINT = 'https://login.salesforce.com/services/oauth2/token';
    public static final String USERNAME = 'User_name';
    public static final String PASSWORD = 'password';
    public static final String CLIENT_ID = '3MVG95jctIhbyCpqKBhfhUgQITLOUF_gUjKgwoNaaVY0VMiyiW6dznmPci7ADZKiH5VSXG79Xowl.XS9zXlfC';
    public static final String CLIENT_SECRET = '1D65EC27D47699AA7F5A36A707EA988D2298202D0B6DB72965BA721312FF433D';       
}
