public with sharing class LeadResponse {
    public string id             {get;set;}      
    public string Name           {get;set;}
    public string FirstName           {get;set;}
    public string LastName           {get;set;}
    public string Email          {get;set;}
    public string Phone          {get;set;}
    public string Company        {get;set;}
    public string MobilePhone    {get;set;}
}
